### ISSUE TITLE
AngularJS, JSLint => block-comment spaces

### ISSUE THREAD

**Issue by iGadget73** [whoisthecoon/atom-block-comment-plus#4]
JSlint has a problem with bock comments without spaces. So how about adding a trailing/leading space to thecomment chars?!

  // defaults to C based comments
  let commentStart = '/\* ';
  let commentEnd = ' */';

**Comment by whoisthecoon** [comment]
Hi @iGadget73, sorry about the delay...

I tried JSLint and didn't have any problem. And I didn't find reference to this in their documentation. Maybe the problem has been fixed on the JSLint side since you posted? Do you still use the package and have the problem?

Thanks.

**Comment by caesarsol** [comment]
Hello @whoisthecoon, I think this has to do with the specific JSLint config that @iGadget73 is using.

I have the same problem, a linter configuration which requires newlines. 
I propose a configuration parameter to let the users choose their commenting style, would that be possible?

Thanks!

**Comment by mezcala** [comment]
Hi @caesarsol thanks for replying.

I fixed @iGadget73's problem by adding a checkbox in the package settings to tell whether you want to add spaces. But then I noticed you need new lines...

So I changed the config param to a selectbox, you can now choose between spaces, new lines or nothing (which is the default value).

I hope it solves the problem.

**Comment by caesarsol** [comment]
Hey @whoisthecoon that is wonderful! I'll try it when I upgrade.

Thanks a lot!!
