### ISSUE TITLE
Would you add julia support?

### ISSUE THREAD

**Issue by specter119** [whoisthecoon/atom-block-comment-plus#5]
`#=`	begin multi-line comment (these are nestable)
`=#`	end multi-line comment

**Comment by whoisthecoon** [comment]
Hi,

This doesn't seem to be a problem. 
What do you meand by "nestable"? Could you provide an example?

**Comment by specter119** [comment]
@whoisthecoon Sorry I just copy it from the [official doc](http://docs.julialang.org/en/release-0.4/stdlib/punctuation/). But i think just `#=` and `=#` will work fine.

**Comment by specter119** [comment]
Maybe, I think it means, the block can be folded and unfolded?

**Comment by whoisthecoon** [comment]
It's done, sorry for the delay!

**Comment by specter119** [comment]
Thank you!
